version: '3'
services:
    web:
        image: asanchez75/pubby:v0.3.3
        ports:
            - "8080:8080"
        environment:
          SPARQL_ENDPOINT: "http://quitstore:3030/sparql"
          PROJECT_HOMEPAGE_URL: "http://limbo-mCloudStatisticsEngine.org"
          PROJECT_NAME: "Limbo Project"
          DEFAULT_RESOURCE: "https://portal.limbo-pr.org/bahnhof/8263"
          DEFAULT_NAMED_GRAPH: "bahnhoefe"
          COMMON_URI_PREFIX: "https://portal.limbo-project.org/bahnhof/"
          WEB_RESOURCE_PREFIX: ""
          PUBBY_ROOT_URL: "http://localhost:8080/pubby/"

        restart: on-failure
    store:
        image: aksw/quitstore
        ports:
           - "3030:80"
        environment:
          QUIT_CONFIGFILE: /config/config.ttl
        volumes:
            - ./data:/data
            - ./storeconfig:/config
        restart: on-failure

volumes:
 store-data:
     
